//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
using IP3_Group4.Models;

#line default
#line hidden

public class _Page_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
      
        ViewBag.Title = "Details";
        Layout = "~/Views/Shared/_Layout.cshtml";
    

#line default
#line hidden

#line 4 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
        foreach (var item in Model.ProductLines) {
            

#line default
#line hidden

#line 5 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
               __o = Html.DisplayFor(modelItem => item.Brand);


#line default
#line hidden

#line 6 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
               __o = Html.DisplayFor(modelItem => item.ItemName);


#line default
#line hidden

#line 7 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
               __o = Html.DisplayFor(modelItem => item.Quantity);


#line default
#line hidden

#line 8 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
                __o = Html.DisplayFor(modelItem => item.Price);


#line default
#line hidden

#line 9 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
                 
            }

#line default
#line hidden

#line 10 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\Details.cshtml"
  __o = Html.ActionLink("Edit", "EditReceipt", new {id = Model.ID});


#line default
#line hidden
}
}
}
