//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
using IP3_Group4.Models;

#line default
#line hidden

public class _Page_EditReceipt_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_EditReceipt_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
  
    ViewBag.Title = "Edit Receipt";


#line default
#line hidden

#line 4 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
if (ViewBag.Message != null)
{
    

#line default
#line hidden

#line 5 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
   __o = ViewBag.Message;


#line default
#line hidden

#line 6 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
          
}

#line default
#line hidden

#line 7 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
using (Html.BeginForm("EditReceipt", "Receipt", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    

#line default
#line hidden

#line 8 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
                               
    

#line default
#line hidden

#line 9 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
          
    

#line default
#line hidden

#line 10 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
__o = Html.ValidationSummary("", new { @class = "text-danger" });


#line default
#line hidden

#line 11 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
                                                               
    

#line default
#line hidden

#line 12 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
   __o = Html.LabelFor(m => m.Shop, new { @class = "col-md-2 control-label" });


#line default
#line hidden

#line 13 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
       __o = Html.TextBoxFor(m => m.Shop, new { @class = "form-control" });


#line default
#line hidden

#line 14 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
          
    

#line default
#line hidden

#line 15 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
   __o = Html.LabelFor(m => m.TotalPrice, new { @class = "col-md-2 control-label" });


#line default
#line hidden

#line 16 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
        __o = Html.TextBoxFor(m => m.TotalPrice, new { @class = "form-control" });


#line default
#line hidden

#line 17 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
          
    

#line default
#line hidden

#line 18 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
   __o = Html.LabelFor(m => m.PurchaseDate, new { @class = "col-md-2 control-label" });


#line default
#line hidden

#line 19 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
       __o = Html.TextBoxFor(m => m.PurchaseDate, new { @class = "form-control" });


#line default
#line hidden

#line 20 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
          

    

#line default
#line hidden

#line 21 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
        for (int i = 0; i < Model.ProductLines.Count; i++)
        {
            

#line default
#line hidden

#line 22 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
               __o = Html.TextBoxFor(m => m.ProductLines[i].ItemName, new { @class = "form-control" });


#line default
#line hidden

#line 23 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
               __o = Html.TextBoxFor(m => m.ProductLines[i].Quantity, new { @class = "form-control" });


#line default
#line hidden

#line 24 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
               __o = Html.TextBoxFor(m => m.ProductLines[i].Price, new { @class = "form-control" });


#line default
#line hidden

#line 25 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
                __o = Model.ProductLines[i].LineTotal;


#line default
#line hidden

#line 26 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
                 
        }

#line default
#line hidden

#line 27 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
            
    


    

#line default
#line hidden

#line 28 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\2\IP3\IP3_Group4\Views\Receipt\EditReceipt.cshtml"
          
}

#line default
#line hidden
}
}
}
