//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 2 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
using IP3_Group4.Data;

#line default
#line hidden

public class _Page_Overview_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Overview_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
      
    ViewBag.Title = "Overview";
    

#line default
#line hidden

#line 4 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.DisplayNameFor(model => model.Shop);


#line default
#line hidden

#line 5 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.DisplayNameFor(model => model.TotalPrice);


#line default
#line hidden

#line 6 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.DisplayNameFor(model => model.PurchaseDate);


#line default
#line hidden

#line 7 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
        foreach (var item in Model) {
        

#line default
#line hidden

#line 8 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.DisplayFor(modelItem => item.Shop);


#line default
#line hidden

#line 9 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
            __o = Html.DisplayFor(modelItem => item.TotalPrice);


#line default
#line hidden

#line 10 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.DisplayFor(modelItem => item.PurchaseDate);


#line default
#line hidden

#line 11 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.ActionLink("Edit", "EditReceipt", new { id = item.ID });


#line default
#line hidden

#line 12 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
           __o = Html.ActionLink("Details", "Details", new { id = item.ID });


#line default
#line hidden

#line 13 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
                using (Html.BeginForm("Delete", "Receipt", new { id = item.ID }))
                {
                    var deleteReceiptModal = $"deleteReceiptModal_{item.ID}";
                    

#line default
#line hidden

#line 14 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
                                                                 __o = deleteReceiptModal;


#line default
#line hidden

#line 15 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
                          
                    

#line default
#line hidden

#line 16 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
                                           __o = deleteReceiptModal;


#line default
#line hidden

#line 17 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
                          
                }

#line default
#line hidden

#line 18 "C:\Users\akilg\AppData\Local\Temp\698B7C7408CE7152D4E3883E8790910B7F1F\3\IP3\IP3_Group4\Views\Receipt\Overview.cshtml"
             
}

#line default
#line hidden
}
}
}
